# Generated by Django 5.2.6 on 2025-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag_code', models.CharField(max_length=10)),
                ('audio_url', models.URLField()),
            ],
            options={
                'db_table': 'audio_languages',
            },
        ),
    ]
